apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-demo.fullname" . }}
  labels:
    {{- include "cloud-demo.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.application.name | quote }}
  APP_VERSION: {{ .Values.application.version | quote }}
  PORT: {{ .Values.application.port | quote }}
  AWS_REGION: {{ .Values.aws.region | quote }}
  S3_BUCKET: {{ .Values.aws.s3Bucket | quote }}
