{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloud-demo.serviceAccountName" . }}
  labels:
    {{- include "cloud-demo.labels" . | nindent 4 }}
  # No IRSA / EKS role annotation.
  # On this K3s cluster the container uses the EC2 instance IAM role.
{{- end }}
